codeapp/models.py
from __future__ import annotations

# python built-in imports
from dataclasses import dataclass
from datetime import date


@dataclass
class Sales:
    order_id: int
    country: str
    item_type: str
    order_priority: str
    order_date: date
    ship_date: date
    units_sold: int
    profit: float

codeapp/__init__.py
# python built-in imports
import logging
import os
from logging.config import dictConfig
from typing import Dict

# python external imports
from dotenv import load_dotenv
from flask import Flask
from redis import Redis

# loading configuration
load_dotenv()

# connecting to the database
host: str = os.getenv("DATABASE_HOST", "127.0.0.1")
port: int = int(os.getenv("DATABASE_PORT", "6379"))
db_number: int = int(os.getenv("DATABASE_DB", "-1"))
password = os.getenv("DATABASE_PASSWORD", "")
db: Redis = Redis(host=host, port=port, db=db_number, password=password)  # type: ignore

if not db.ping():
    raise ValueError("Database could not connect! Check DB parameters and try again.")

# configuring the logging
# for more info, check:
# https://docs.python.org/3.10/howto/logging.html
# this configuration writes to a file and to the console
dictConfig(
    {
        "version": 1,
        "formatters": {
            "default": {
                "format": "[%(asctime)s] [%(levelname)s] [%(name)s] "
                "[%(module)s:%(lineno)s] - %(message)s",
            }
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "default",
            },
            "to_file": {
                "level": "DEBUG",
                "formatter": "default",
                "class": "logging.handlers.RotatingFileHandler",
                "filename": "logs/messages.log",
                "maxBytes": 5000000,
                "backupCount": 10,
            },
        },
        "root": {
            "level": "DEBUG",
            "handlers": ["console", "to_file"],
        },
    }
)
logging.getLogger("matplotlib").setLevel(logging.WARNING)
logging.getLogger("PIL").setLevel(logging.WARNING)


def create_app() -> Flask:
    app: Flask = Flask(__name__)

    if os.getenv("APP_MODE") == "PRODUCTION":
        os.environ["FLASK_DEBUG"] = "0"  # pragma: no cover
    else:
        os.environ["FLASK_DEBUG"] = "1"  # pragma: no cover

    # register blueprints
    from codeapp.routes import bp  # pylint: disable=import-outside-toplevel

    app.register_blueprint(bp)

    # shell context for flask cli
    @app.shell_context_processor
    def ctx() -> Dict[str, object]:  # pragma: no cover
        return {"app": app, "db": db}

    return app

codeapp/routes.py
# pylint: disable=cyclic-import
"""
File that contains all the routes of the application.
This is equivalent to the "controller" part in a model-view-controller architecture.
In the final project, you will need to modify this file to implement your project.
"""
# built-in imports
import io

# external imports
from flask import Blueprint, jsonify, render_template
from flask.wrappers import Response as FlaskResponse
from matplotlib.figure import Figure
from werkzeug.wrappers.response import Response as WerkzeugResponse

from codeapp.models import Sales

# internal imports
from codeapp.utils import calculate_statistics, get_data_list, prepare_figure

# define the response type
Response = str | FlaskResponse | WerkzeugResponse

bp = Blueprint("bp", __name__, url_prefix="/")


################################### web page routes ####################################


@bp.get("/")  # root route
def home() -> Response:
    dataset: list[Sales] = get_data_list()
    counter: dict[str, float] = calculate_statistics(dataset)
    return render_template("home.html", counter=counter)


@bp.get("/image")
def image() -> Response:
    dataset: list[Sales] = get_data_list()
    counter: dict[str, float] = calculate_statistics(dataset)
    # creating the plot
    fig = Figure()
    fig.gca().bar(
        list(sorted(counter.keys())),
        [counter[x] for x in sorted(counter.keys())],
        color="skyblue",
        zorder=1,
    )

    fig.gca().set_xlabel("Item type")
    fig.gca().set_ylabel("Average profit")
    fig.gca().set_title("Average profit per Item type")
    ticks = list(sorted(counter.keys()))
    fig.gca().set_xticks(ticks)
    fig.gca().set_xticklabels(list(sorted(counter.keys())), rotation=90)
    fig.tight_layout()

    ################ START -  THIS PART MUST NOT BE CHANGED BY STUDENTS ################
    # create a string buffer to hold the final code for the plot
    output = io.StringIO()
    fig.savefig(output, format="svg")
    # output.seek(0)
    final_figure = prepare_figure(output.getvalue())
    return FlaskResponse(final_figure, mimetype="image/svg+xml")


@bp.get("/about")
def about() -> Response:
    return render_template("about.html")


################################## web service routes ##################################


@bp.get("/json-dataset")
def get_json_dataset() -> Response:
    dataset: list[Sales] = get_data_list()
    return jsonify(dataset)


@bp.get("/json-stats")
def get_json_stats() -> Response:
    dataset: list[Sales] = get_data_list()
    counter: dict[str, float] = calculate_statistics(dataset)
    return jsonify(counter)

codeapp/templates/about.html
{% extends "base.html" %}
{% block content %}
<h1 id="about_header">About</h1>
<p> Moa Persson and Linnea Sandell </p>
{% endblock content %}

codeapp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Carlos Natalino">
    <title>EEN060/EEN065 - Example Project</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <meta name="theme-color" content="#7952b3">
    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-primary">
      <div class="container-fluid">
        <a id="navbar_brand" class="navbar-brand" href="{{ url_for('bp.home') }}">EEN060/EEN065</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <!-- left side -->
          <ul class="navbar-nav me-auto mb-2 mb-md-0">

            <li class="nav-item">
              <a
                {% set class="nav-link" %}
                {% if request.url_rule.endpoint == "bp.home" %}
                {% set class = class ~ " active" %}
                {% endif %}
                class="{{ class }}" 
                aria-current="page" 
                href="{{ url_for('bp.home') }}">
                <i class="bi bi-app"></i>
                Home
              </a>
            </li>

            <li class="nav-item">
              <a aria-current="page"
                {% set class="nav-link" %}
                {% if request.url_rule.endpoint == "bp.about" %}
                {% set class = class ~ " active" %}
                {% endif %}
                class="{{ class }}" 
                href="{{ url_for('bp.about') }}">
                <i class="bi bi-patch-question"></i>
                About
              </a>
            </li>

          </ul>
        </div>
      </div>
    </nav>
    <main class="container">
      <div class="row">
        <div class="col-md-12">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
        </div>
      </div>
      <div class="bg-light p-5 rounded">
        {% block content %}{% endblock %}
      </div>
    </main>
    <footer style="background-color: #deded5;">
      <div class="text-center p-3" style="background-color: #0dcaf0a1;">
        &copy; 2023 Copyright: <b>Student 1 and Student 2</b>
      </div>
    </footer>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

codeapp/templates/home.html
{% extends "base.html" %}
{% block content %}
<h1 id="homepage_header">Final project</h1>
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Item type</th>
            <th>Average profit</th>
        </tr>
    </thead>
    <tbody>
        {% for item_type, count in counter.items()|sort(attribute='0') %}
            <tr>
                <td>{{ item_type }}</td>
                <td>{{ count }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>


<img src="{{ url_for('bp.image') }}" class="rounded mx-auto d-block" alt="Plot with analysis">

{% endblock content %}